# Generated by Django 3.2.21 on 2023-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
